### ISSUE TITLE
Quote, Quasi-Quote, and Vector support missing

### ISSUE THREAD

**Issue by ghost** [dryruby/sxp.rb#16]
The S-Expression parser works fine for simple S-Expressions,
but one can't parse quoted expressions (`'hello`) or quasi-quoted expressions using it,
also vectors (`#(hello)`) are not supported.

I understand, that they aren't part of the real bare bone S-Expression thing,
but they are supported by a big majority of LISPs out there.

Implementing them directly would break compatibility, but they could be implemented using a special flag.

```ruby
SXP.read "(hello 'quoted #(world))", [:vector, :quote]     #=> [:hello, [:quote, :quoted], [:vector, :world]]
```

**Comment by ac1235** [comment]
Sorry, I used it the wrong way... most of this is implemented.
Excuse me, I will immediately close this issue.

**Comment by gkellogg** [comment]
The gem supports different readers with differences in supported syntax. You may want to consider a new reader to support your needs, unless you feel that the "scheme" reader, say, should,do this natively. Pull requests welcome.

**Comment by ac1235** [comment]
I will look into the source code an probably formulate the pull request if I find it.
It's just, that this is part of lisp, just like strings and numbers are.

**Comment by gkellogg** [comment]
This is fully supported now, although not using the default Basic reader, but with the Common Lisp reader. This makes use of the Ruby standard `Vector` class and round-trips.

```
SXP::Reader::CommonLisp.read "(hello 'quoted #(world))"
  # => [:hello, [:quote, :quoted], Vector[:world]]
```
