### ISSUE TITLE
It seems that float inf, nan do not follow lisp convention

### ISSUE THREAD

**Issue by o314** [dryruby/sxp.rb#18]
Float are handled in [sxp writer](https://github.com/dryruby/sxp.rb/blob/develop/lib/sxp/writer.rb#L108-L115) as :

```ruby
  def to_sxp
    case
      when nan? then 'nan.'
      when infinite? then (infinite? > 0 ? '+inf.' : '-inf.')
      else to_s
    end
  end
end
```

R6rs, guile use `nan.0`, `+inf.0`, `-inf.0` rather than `nan.`, `+inf.`, `-inf.`

Shouldn't these conventions be followed ?

--
See

- https://www.gnu.org/software/guile/manual/html_node/Reals-and-Rationals.html
- http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html

**Comment by gkellogg** [comment]
Seems reasonable to me. I believe @artob wrote this originally. Hearing no concerns, I'd say we make the change.

**Comment by artob** [comment]
Looks good to me.

**Comment by o314** [comment]
Thanks you both for your quick feedback and follow-up.

**Comment by gkellogg** [comment]
I’ll release an update to the gem today.

**Comment by o314** [comment]
It seems femtolisp follows this convention too 

```c
    if (tok[0] == '+') {
        if (!strcmp(tok,"+NaN") || !strcasecmp(tok,"+nan.0")) {
            if (pval) *pval = mk_double(fl_ctx, D_PNAN);
            return 1;
        }
        if (!strcmp(tok,"+Inf") || !strcasecmp(tok,"+inf.0")) {
            if (pval) *pval = mk_double(fl_ctx, D_PINF);
            return 1;
        }
    }
    else if (tok[0] == '-') {
        if (!strcmp(tok,"-NaN") || !strcasecmp(tok,"-nan.0")) {
            if (pval) *pval = mk_double(fl_ctx, D_NNAN);
            return 1;
        }
        if (!strcmp(tok,"-Inf") || !strcasecmp(tok,"-inf.0")) {
            if (pval) *pval = mk_double(fl_ctx, D_NINF);
            return 1;
        }
```

https://github.com/JuliaLang/julia/blob/master/src/flisp/read.c#L72-L90
