### ISSUE TITLE
Bug: Reader::CommonLisp doesn't work as documented

### ISSUE THREAD

**Issue by marnen** [dryruby/sxp.rb#21]
**Describe the bug**
The README claims that Reader::CommonLisp treats special atoms specially:

```
SXP::Reader::CommonLisp.read %q((or t nil))          #=> [:or, true, nil]
```

However, in practice, Reader::CommonLisp doesn't map Lisp `t` and `nil` to Ruby `true` and `false`; it just treats them like any other atoms and converts them to Ruby symbols:

```
irb(main):008:0> SXP::VERSION.to_s
=> "1.2.2"
irb(main):009:0> SXP::Reader::CommonLisp.read %q((or t nil)) # the same example from the README
=> [:or, :t, :nil]
irb(main):010:0> RUBY_VERSION
=> "2.7.1"
```

I think this is a bug. Either the documentation or the gem should be updated.

**Comment by gkellogg** [comment]
@marnen, see if PR #22 solves the issue. It adds case-insensitive atoms 't' and 'nil'. I didn't see any other such tokens defined in CommonLisp beyond those defined in the Basic reader.

**Comment by marnen** [comment]
Thanks, I’ll look. I think it’s probably more sensible to have Lisp `nil` map to Ruby `nil` than to `false`…

**Comment by gkellogg** [comment]
> Thanks, I’ll look. I think it’s probably more sensible to have Lisp `nil` map to Ruby `nil` than to `false`…

The are both Falsey, so that would be fine.

**Comment by marnen** [comment]
My thoughts exactly. The falsiness of Ruby nil means that the Common Lisp ambiguity between nil and false is OK, if not great.

**Comment by marnen** [comment]
Thank you for fixing this! For future reference, though, this was probably a breaking change, so I'm not sure it should have been a patch release (although it was a bugfix).

BTW, I appreciate this gem _so much_. I'm using this on a project that I'm translating from Lisp to Ruby, so it's coming in handy for constructing Lisp expressions and parsing Lisp output in my RSpec tests.
